name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: run terraform pre-commit hooks
        uses: ./
      - name: initialize Terraform
        run: terraform init --backend=false
      - name: Plan Terraform
        run: terraform plan 
      # - name: apply Terraform
      #   run: terraform apply --backend=false