name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: AWS Authentication.....
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          run: aws s3 ls
      - name: run terraform pre-commit hooks
        uses: ./
      - name: initialize Terraform
        run: terraform init 
      # - name: Plan Terraform
      #   run: terraform plan 
      # - name: apply Terraform
      #   run: terraform apply 